### ISSUE TITLE
Import ticks from MountainProject and keep notes of the process. What works well? What can be improved?

### ISSUE THREAD

**Issue by dww3000** [OpenBeta/open-tick-list#7]
This task is optional, but helpful if you are able and willing.

Importing ticks from Mountain Project will give us a starting point of what works well and what can be improved with the Climb Log project. 

Share your results here: https://discord.com/channels/815145484003967026/1101556924501205112

**Comment by musoke** [comment]
~~Blocked by https://github.com/OpenBeta/open-tacos/pull/842~~

Now fixed

**Comment by musoke** [comment]
I'm closing this as it is "done" in the project board.

**Comment by vnugent** [comment]
I think we can create a Google form and ask users to give feedback whenever they do an import.
